from __future__ import annotations

from tech_scan.models import DIM_BACKEND

from .common import (
    Rule,
    any_detector,
    body_detector,
    cookie_name_detector,
    cookie_value_detector,
    embedded_url_detector,
    global_detector,
    header_detector,
    meta_detector,
    script_body_detector,
    script_url_detector,
    url_detector,
)


RULES = [
    Rule("ASP.NET", DIM_BACKEND, 95, header_detector("x-aspnet-version", r".+")),
    Rule("ASP.NET", DIM_BACKEND, 90, header_detector("x-powered-by", r"\basp\.net\b")),
    Rule("ASP.NET", DIM_BACKEND, 90, cookie_name_detector(r"ASP\.NET_SessionId")),
    Rule("ASP.NET", DIM_BACKEND, 70, url_detector(r"\.aspx?(?:[/?#]|$)")),
    Rule("ASP.NET", DIM_BACKEND, 60, embedded_url_detector(r"\.aspx?(?:[/?#]|$)")),
    Rule("ASP.NET Web Forms", DIM_BACKEND, 95, body_detector(r"name=[\"']__(VIEWSTATE|EVENTVALIDATION|VIEWSTATEGENERATOR)[\"']|id=[\"']__(VIEWSTATE|EVENTVALIDATION|VIEWSTATEGENERATOR)[\"']", "web forms state field")),
    Rule("ASP.NET Web Forms", DIM_BACKEND, 90, body_detector(r"(WebResource|ScriptResource)\.axd(?:[?\"'])", "web forms resource handler")),
    Rule("ASP.NET MVC/Core", DIM_BACKEND, 85, body_detector(r"__RequestVerificationToken", "asp.net antiforgery token")),
    Rule("ASP.NET Core", DIM_BACKEND, 90, header_detector("server", r"\bkestrel\b")),
    Rule("ASP.NET Core", DIM_BACKEND, 85, cookie_name_detector(r"\.AspNetCore\.")),
    Rule("Classic ASP", DIM_BACKEND, 85, cookie_name_detector(r"ASPSESSIONID[A-Z0-9]*")),
    Rule("Classic ASP", DIM_BACKEND, 65, url_detector(r"\.asp(?:[/?#]|$)")),
    Rule("Classic ASP", DIM_BACKEND, 55, embedded_url_detector(r"\.asp(?:[/?#]|$)")),
    Rule("Java", DIM_BACKEND, 70, cookie_name_detector(r"(^|\n)JSESSIONID($|\n)")),
    Rule("Java", DIM_BACKEND, 75, header_detector("server", r"apache-coyote|jetty|weblogic|gse")),
    Rule("Spring", DIM_BACKEND, 90, body_detector(r"Whitelabel Error Page|springframework|Spring Boot", "spring marker")),
    Rule("Spring", DIM_BACKEND, 80, header_detector("x-application-context", r".+")),
    Rule("Spring Security", DIM_BACKEND, 80, body_detector(r"name=[\"']_csrf[\"']|csrfParameterName|csrfHeaderName", "spring csrf marker")),
    Rule("Java EE/Jakarta EE", DIM_BACKEND, 80, body_detector(r"javax\.|jakarta\.|JavaServer Faces", "java ee marker")),
    Rule("JavaServer Faces", DIM_BACKEND, 90, body_detector(r"javax\.faces\.ViewState|jakarta\.faces\.ViewState", "jsf view state")),
    Rule("JavaServer Faces", DIM_BACKEND, 85, body_detector(r"PrimeFaces|RichFaces|IceFaces|javax\.faces|jakarta\.faces", "jsf component marker")),
    Rule("JavaServer Faces", DIM_BACKEND, 70, url_detector(r"\.xhtml(?:[/?#]|$)")),
    Rule("JavaServer Faces", DIM_BACKEND, 60, embedded_url_detector(r"\.xhtml(?:[/?#]|$)")),
    Rule("JSP", DIM_BACKEND, 85, body_detector(r"\.jsp(?:x)?(?:\b|[?\"'])|JSP Page|JasperException", "jsp marker")),
    Rule("JSP", DIM_BACKEND, 70, url_detector(r"\.jspx?(?:[/?#]|$)")),
    Rule("JSP", DIM_BACKEND, 60, embedded_url_detector(r"\.jspx?(?:[/?#]|$)")),
    Rule("Java Servlet", DIM_BACKEND, 70, url_detector(r"\.(do|action)(?:[/?#]|$)")),
    Rule("Java Servlet", DIM_BACKEND, 60, embedded_url_detector(r"\.(do|action)(?:[/?#]|$)")),
    Rule("Apache Tomcat", DIM_BACKEND, 90, header_detector("server", r"tomcat|coyote")),
    Rule("Apache Tomcat", DIM_BACKEND, 90, header_detector("x-powered-by", r"\btomcat\b")),
    Rule("Jetty", DIM_BACKEND, 90, header_detector("server", r"jetty")),
    Rule("JBoss/WildFly", DIM_BACKEND, 90, header_detector("server", r"jboss|wildfly")),
    Rule("PHP", DIM_BACKEND, 90, header_detector("x-powered-by", r"php")),
    Rule("PHP", DIM_BACKEND, 85, cookie_name_detector(r"PHPSESSID")),
    Rule("PHP", DIM_BACKEND, 70, url_detector(r"\.php(?:[/?#]|$)")),
    Rule("PHP", DIM_BACKEND, 60, embedded_url_detector(r"\.php(?:[/?#]|$)")),
    Rule("Laravel", DIM_BACKEND, 90, cookie_name_detector(r"laravel_session|XSRF-TOKEN")),
    Rule("Laravel", DIM_BACKEND, 80, body_detector(r"name=[\"']_token[\"']", "laravel csrf field")),
    Rule("Laravel", DIM_BACKEND, 85, cookie_value_detector(r"(?im)^(laravel_session|XSRF-TOKEN)=((eyJpdiI6)|(%7B%22iv%22))", "laravel encrypted cookie")),
    Rule("Laravel", DIM_BACKEND, 80, body_detector(r"Whoops, looks like something went wrong|Illuminate\\|Laravel\\s+(?:Framework|Application|Exception|Error)", "laravel error/debug marker")),
    Rule("Django", DIM_BACKEND, 85, cookie_name_detector(r"(^|\n)(csrftoken|sessionid)($|\n)")),
    Rule("Django", DIM_BACKEND, 85, body_detector(r"name=[\"']csrfmiddlewaretoken[\"']", "django csrf marker")),
    Rule("Django", DIM_BACKEND, 85, cookie_name_detector(r"(^|\n)django_language($|\n)")),
    Rule("Python", DIM_BACKEND, 80, header_detector("server", r"(^|\s)python(?:/|$)")),
    Rule("Python", DIM_BACKEND, 80, header_detector("server", r"werkzeug|gunicorn|cherrypy")),
    Rule("Flask", DIM_BACKEND, 90, header_detector("server", r"werkzeug")),
    Rule("Ruby", DIM_BACKEND, 80, header_detector("server", r"mongrel|ruby(?:/|$)")),
    Rule("Ruby on Rails", DIM_BACKEND, 85, cookie_name_detector(r"(^|\n)(_[a-z0-9]+_session|_session_id)($|\n)")),
    Rule("Ruby on Rails", DIM_BACKEND, 85, header_detector("server", r"mod_(?:rails|rack)")),
    Rule("Ruby on Rails", DIM_BACKEND, 85, header_detector("x-powered-by", r"mod_(?:rails|rack)")),
    Rule("Ruby on Rails", DIM_BACKEND, 70, body_detector(r"<meta[^>]+name=[\"']csrf-param[\"'][^>]+content=[\"']authenticity_token[\"']|<meta[^>]+content=[\"']authenticity_token[\"'][^>]+name=[\"']csrf-param[\"']", "rails csrf param meta")),
    Rule("Ruby on Rails", DIM_BACKEND, 65, body_detector(r"/assets/application-[a-z0-9]{32}\.js", "rails asset pipeline script")),
    Rule("Ruby on Rails", DIM_BACKEND, 75, global_detector(r"ReactOnRails|__REACT_ON_RAILS_EVENT_HANDLERS_RAN_ONCE__|_rails_loaded")),
    Rule("Express", DIM_BACKEND, 90, header_detector("x-powered-by", r"express")),
    Rule("Node.js", DIM_BACKEND, 80, header_detector("x-powered-by", r"node\.?js")),
    Rule("Koa", DIM_BACKEND, 90, header_detector("x-powered-by", r"^koa$")),
    Rule("Hono", DIM_BACKEND, 90, header_detector("x-powered-by", r"^hono$")),
    Rule("Sails.js", DIM_BACKEND, 90, header_detector("x-powered-by", r"^sails(?:$|[^a-z0-9])")),
    Rule("Sails.js", DIM_BACKEND, 85, cookie_name_detector(r"sails\.sid")),
    Rule("total.js", DIM_BACKEND, 90, header_detector("x-powered-by", r"^total\.js")),
    Rule("Bun", DIM_BACKEND, 90, header_detector("x-powered-by", r"^bun$")),
    Rule("Symfony", DIM_BACKEND, 85, cookie_name_detector(r"sf_redirect")),
    Rule("Symfony", DIM_BACKEND, 75, global_detector(r"Sfjs")),
    Rule("CodeIgniter", DIM_BACKEND, 85, cookie_name_detector(r"ci_(csrf_token|session)")),
    Rule("CodeIgniter", DIM_BACKEND, 80, body_detector(r"name=[\"']ci_csrf_token[\"']", "codeigniter csrf marker")),
    Rule("CakePHP", DIM_BACKEND, 85, cookie_name_detector(r"cakephp")),
    Rule("CakePHP", DIM_BACKEND, 80, meta_detector("application-name", r"cakephp", "cakephp application meta")),
    Rule("Yii", DIM_BACKEND, 85, cookie_name_detector(r"yii_csrf_token")),
    Rule("Yii", DIM_BACKEND, 80, any_detector(
        body_detector(r"name=[\"']yii_csrf_token[\"']", "yii marker"),
        script_body_detector(r"yii\.(?:validation|activeform)|yiiActiveForm", "script body"),
        script_url_detector(r"yii\.(?:validation|activeform)\.js"),
    )),
    Rule("Livewire", DIM_BACKEND, 85, any_detector(
        body_detector(r"\bwire:[a-z-]+", "livewire marker"),
        script_body_detector(r"Livewire\.|livewire_token|livewire(?:\.min)?\.js", "script body"),
        script_url_detector(r"livewire(?:\.min)?\.js"),
    )),
    Rule("Adobe ColdFusion", DIM_BACKEND, 85, cookie_name_detector(r"(CFID|CFTOKEN)")),
    Rule("Adobe ColdFusion", DIM_BACKEND, 80, any_detector(
        body_detector(r"\.cfm(?:[?\"']|$)|/cfajax/", "coldfusion marker", True),
        script_url_detector(r"/cfajax/"),
    )),
]
